"use client";

import {
  ContactRound, PlaneTakeoff, Users, PlaneLanding, BookOpen, Building2, Bus, Map, Landmark,
  Utensils, ShoppingBag, ClipboardList, ShieldCheck, Hexagon, Circle, Building, Network,
  HeartHandshake, Plane, Scale, BadgeCheck, Workflow, Eye, Smartphone, MapPin, BrainCircuit,
  GitMerge, LayoutDashboard, Languages, Menu, X, ChevronRight, ChevronDown, ArrowRight,
  Search, Star, Quote, Phone, Mail, Globe, Instagram, Facebook, Twitter, Youtube, CheckCircle2,
  Clock, AlertTriangle, Loader2, LogIn, LogOut, Newspaper, Settings, MessageSquare, HelpCircle,
  Sparkles, Calendar, Tag, TrendingUp, Inbox, UserPlus, ExternalLink, Award, MoonStar,
  Grid3X3, Boxes, FileText, GraduationCap, Send, Pencil, Trash2, Plus, Save, RotateCcw,
  KeyRound, ShieldAlert, Target, HeartPulse, Wallet, BarChart3, Wifi, Printer, Download,
  Compass, Handshake, TentTree, ScrollText, Info, Ban, RefreshCw, User,
  Webhook, QrCode, Braces, Terminal, Activity, PlugZap, ScanLine, RadioTower,
  Timer, DatabaseZap, Satellite, Radar, Cable, Fingerprint, ShieldEllipsis, EyeOff, Server, HardDrive, Cpu, Gauge,
  Sun, Moon, Monitor, Bell, BellRing, MessageCircle, UserCog, Megaphone,
} from "lucide-react";

export const ICONS: Record<string, React.ComponentType<{ className?: string; strokeWidth?: number }>> = {
  passport: ContactRound,
  "plane-takeoff": PlaneTakeoff,
  users: Users,
  "plane-landing": PlaneLanding,
  "book-open": BookOpen,
  "building-2": Building2,
  bus: Bus,
  map: Map,
  landmark: Landmark,
  utensils: Utensils,
  "shopping-bag": ShoppingBag,
  "clipboard-list": ClipboardList,
  "shield-check": ShieldCheck,
  hexagon: Hexagon,
  circle: Circle,
  building: Building,
  network: Network,
  "heart-handshake": HeartHandshake,
  plane: Plane,
  scale: Scale,
  "badge-check": BadgeCheck,
  workflow: Workflow,
  eye: Eye,
  smartphone: Smartphone,
  "map-pin": MapPin,
  "brain-circuit": BrainCircuit,
  "git-merge": GitMerge,
  "layout-dashboard": LayoutDashboard,
  languages: Languages,
  menu: Menu,
  x: X,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "arrow-right": ArrowRight,
  search: Search,
  star: Star,
  quote: Quote,
  phone: Phone,
  mail: Mail,
  globe: Globe,
  instagram: Instagram,
  facebook: Facebook,
  twitter: Twitter,
  youtube: Youtube,
  "check-circle-2": CheckCircle2,
  clock: Clock,
  "alert-triangle": AlertTriangle,
  "loader-2": Loader2,
  login: LogIn,
  logout: LogOut,
  newspaper: Newspaper,
  settings: Settings,
  "message-square": MessageSquare,
  "help-circle": HelpCircle,
  sparkles: Sparkles,
  megaphone: Megaphone,
  calendar: Calendar,
  tag: Tag,
  "trending-up": TrendingUp,
  inbox: Inbox,
  "user-plus": UserPlus,
  "external-link": ExternalLink,
  award: Award,
  "moon-star": MoonStar,
  "grid-3x3": Grid3X3,
  boxes: Boxes,
  "file-text": FileText,
  "graduation-cap": GraduationCap,
  send: Send,
  pencil: Pencil,
  trash: Trash2,
  plus: Plus,
  save: Save,
  rotate: RotateCcw,
  keyround: KeyRound,
  "shield-alert": ShieldAlert,
  target: Target,
  "heart-pulse": HeartPulse,
  wallet: Wallet,
  "bar-chart-3": BarChart3,
  wifi: Wifi,
  printer: Printer,
  download: Download,
  compass: Compass,
  handshake: Handshake,
  "tent-tree": TentTree,
  "scroll-text": ScrollText,
  info: Info,
  ban: Ban,
  refresh: RefreshCw,
  user: User,
  webhook: Webhook,
  "qr-code": QrCode,
  braces: Braces,
  terminal: Terminal,
  activity: Activity,
  plug: PlugZap,
  scan: ScanLine,
  "radio-tower": RadioTower,
  timer: Timer,
  "database-zap": DatabaseZap,
  satellite: Satellite,
  radar: Radar,
  cable: Cable,
  fingerprint: Fingerprint,
  "shield-ellipsis": ShieldEllipsis,
  "eye-off": EyeOff,
  server: Server,
  "hard-drive": HardDrive,
  cpu: Cpu,
  gauge: Gauge,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  bell: Bell,
  "bell-ring": BellRing,
  "message-circle": MessageCircle,
  "user-cog": UserCog,
};

export function Icon({
  name,
  className,
  strokeWidth = 2,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = ICONS[name] || ICONS.hexagon;
  return <Cmp className={className} strokeWidth={strokeWidth} />;
}
